// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {uuid} from '../models';
import {models} from '../models';

export function DeleteAccount(arg1:string):Promise<void>;

export function GetAllAccounts():Promise<any>;

export function GetOneAccount(arg1:uuid.UUID):Promise<models.Account>;
