// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1) {
  return window['go']['account']['account']['DeleteAccount'](arg1);
}

export function GetAllAccounts() {
  return window['go']['account']['account']['GetAllAccounts']();
}

export function GetOneAccount(arg1) {
  return window['go']['account']['account']['GetOneAccount'](arg1);
}
