// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccounts() {
  return window['go']['account']['account']['GetAccounts']();
}

export function GetOneAccount(arg1) {
  return window['go']['account']['account']['GetOneAccount'](arg1);
}
