// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function CreateAccount(arg1:context.Context,arg2:string,arg3:string):Promise<string|boolean>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function TestyLogin(arg1:string,arg2:string):Promise<string>;
