// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2) {
  return window['go']['auth']['auth']['CreateAccount'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['auth']['auth']['Login'](arg1, arg2);
}
