// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CreateAccount(arg1:string,arg2:string):Promise<boolean>;

export function Login(arg1:string,arg2:string):Promise<models.Account>;

export function TestyLogin(arg1:string,arg2:string):Promise<string>;
